server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters: #GatewayFilter是网关中提供的一种过滤器，可以对进入网关的请求和微服务返回的响应做处理：
#            - AddRequestHeader=Truth,Itwhy is aowsome!
        - id: order-service
          uri: lb://orderservice # 路由的目标地址
          predicates:
            - Path=/order/** #            - Before=2031-01-20T17:42:47.789-07:00[Asia/Shanghai]
      #   断言工厂作用：读取用户配置的断言规则，然后解析成对应的判断条件
      #   Path=/order/**:对用户请求路径做判断
      default-filters: #默认过滤器，对所有的路由都生效
        - AddRequestHeader=Truth,Itwhy is 666!
#解决跨域问题-CORS
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期