server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userservice # eureka的服务名称
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos服务地址
#      discovery:
#        cluster-name: SH #集群名称，这里HZ代指杭州
        #namespace: fd25d04d-d51c-4ff5-ab1c-b7a4efe719fc
#        ephemeral: false #设置为非临时实例

#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: cn.itwhy.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itwhy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地属性local
