server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice # eureka的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
#      server-addr: localhost:80 #nacos集群地址
      discovery:
        cluster-name: SH # 集群名称
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel控制台地址
      #namespace: fd25d04d-d51c-4ff5-ab1c-b7a4efe719fc #命名空间，填上图中的命名空间id
      web-context-unify: false #关闭context整合
#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: cn.itwhy.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itwhy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice: #只针对某个微服务而言
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
#配置feign
feign:
  httpclient: # 支持HttpClient的开关
    enabled: true
    max-connections: 200 #最大连接数,jmeter压测决定
    max-connections-per-route: 50 #单个路径的最大连接数
  client:
    config:
      default:
        loggerLevel: FULL
  sentinel:
    enabled: true #开启Feign对Sentinel的支持